# Generated by Django 5.1.5 on 2026-10-04 01:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0004_remove_clothing_back_image_path_and_more'),
        ('outfits', '0001_initial'),
        ('ratings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(condition=models.Q(('clothing__isnull', False)), fields=('user', 'clothing'), name='unique_clothing_rating'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(condition=models.Q(('outfit__isnull', False)), fields=('user', 'outfit'), name='unique_outfit_rating'),
        ),
    ]
