# Generated by Django 5.1.5 on 2026-10-04 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0003_alter_clothing_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothing',
            name='back_image_path',
        ),
        migrations.RemoveField(
            model_name='clothing',
            name='front_image_path',
        ),
        migrations.AddField(
            model_name='clothing',
            name='back_image',
            field=models.ImageField(blank=True, upload_to='clothing/'),
        ),
        migrations.AddField(
            model_name='clothing',
            name='front_image',
            field=models.ImageField(blank=True, upload_to='clothing/'),
        ),
    ]
