# Generated by Django 5.1.5 on 2026-10-04 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0004_remove_clothing_back_image_path_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothing',
            old_name='back_image',
            new_name='original_back_image',
        ),
        migrations.RenameField(
            model_name='clothing',
            old_name='front_image',
            new_name='original_front_image',
        ),
        migrations.AddField(
            model_name='clothing',
            name='processed_back_image',
            field=models.ImageField(blank=True, upload_to='clothing/processed/'),
        ),
        migrations.AddField(
            model_name='clothing',
            name='processed_front_image',
            field=models.ImageField(blank=True, upload_to='clothing/processed/'),
        ),
    ]
